// ============================================================
//  data.js – StadeTours – Circuits football & stades
// ============================================================

const COUNTRIES = [
  { id: "spain",       name: "Espagne",    flag: "🇪🇸", image: "images/espagne.avif", circuits: 3, tagline: "Passion, rivalités & légendes du football" },
  { id: "france",      name: "France",     flag: "🇫🇷", image: "images/france.jpg", circuits: 3, tagline: "Les Bleus, les clubs & les temples du foot" },
  { id: "italy",       name: "Italie",     flag: "🇮🇹", image: "images/italie.jpg", circuits: 4, tagline: "La passion italienne pour il calcio" },
  { id: "germany",     name: "Allemagne",  flag: "🇩🇪", image: "images/germany.jpg", circuits: 3, tagline: "Bundesliga, efficacité & ferveur populaire" },
  { id: "england",     name: "Angleterre", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿", image: "images/england.jpg", circuits: 4, tagline: "Le berceau du football mondial" },
  { id: "portugal",    name: "Portugal",   flag: "🇵🇹", image: "images/portugal.jpg", circuits: 2, tagline: "Ronaldo, Eusébio & la saudade du ballon" },
  { id: "netherlands", name: "Pays-Bas",   flag: "🇳🇱", image: "images/netherlands.webp", circuits: 2, tagline: "Football total, Ajax & l'école néerlandaise" },
  { id: "brazil",      name: "Brésil",     flag: "🇧🇷", image: "images/brazil.jpg", circuits: 2, tagline: "Le jogo bonito et les temples du samba" },
];

const CIRCUITS = [
  // ── ESPAGNE ──────────────────────────────────────────────
  {
    id: "bcn-1",
    country: "spain",
    city: "Barcelone",
    title: "Camp Nou & Musée du FC Barcelone",
    description: "Vivez une expérience unique au Camp Nou, le plus grand stade d'Europe. Découvrez les coulisses du FC Barcelone, visitez le musée du club riche de décennies de gloire, touchez les trophées et marchez dans les vestiaires des légendes. Un circuit incontournable pour tout fan du Barça.",
    duration: 2,
    price: 750,
    rating: 4.9,
    reviews: 512,
    activities: ["stadium", "museum", "city-tour"],
    highlights: ["Visite du Camp Nou (coulisses)", "Musée officiel du FC Barcelone", "Galerie des trophées & Ballons d'Or", "Vestiaires & salle de presse", "Boutique officielle du Barça", "Photo sur la pelouse"],
    image: "images/CampNou.jpeg",
    popular: true,
    tag: "Best-seller",
  },
  {
    id: "mad-1",
    country: "spain",
    city: "Madrid",
    title: "Santiago Bernabéu – La Maison du Real",
    description: "Le Santiago Bernabéu est le temple du football mondial. Cette visite exclusive vous plonge dans l'histoire du club le plus titré en Ligue des Champions. Du musée aux loges présidentielles, vivez le Real Madrid de l'intérieur.",
    duration: 2,
    price: 799,
    rating: 4.9,
    reviews: 431,
    activities: ["stadium", "museum", "city-tour"],
    highlights: ["Visite du Bernabéu rénové", "Musée du Real Madrid", "Salle des 15 Ligues des Champions", "Loge présidentielle & tribune d'honneur", "Vestiaires des joueurs", "Boutique officielle Madridista"],
    image: "images/SantiagoBernabeu.jpeg",
    popular: true,
    tag: "Coup de cœur",
  },
  {
    id: "sev-1",
    country: "spain",
    city: "Séville",
    title: "Ramón Sánchez-Pizjuán – Le Temple du Séville FC",
    description: "Séville FC, six fois vainqueur de la Ligue Europa. Visitez le Sánchez-Pizjuán, l'un des stades les plus chauds d'Espagne, son musée et ses trophées européens dans une ville passionnée de football.",
    duration: 2,
    price: 599,
    rating: 4.7,
    reviews: 134,
    activities: ["stadium", "museum"],
    highlights: ["Stade Ramón Sánchez-Pizjuán", "Musée du FC Séville", "6 Coupes UEFA/Europa League", "Vestiaires & pelouse", "Histoire du derby sévillan", "Boutique officielle Séville FC"],
    image: "https://images.unsplash.com/photo-1489944440615-453fc2b6a9a9?w=900&q=80",
    popular: false,
    tag: null,
  },

  // ── FRANCE ───────────────────────────────────────────────
  {
    id: "par-1",
    country: "france",
    city: "Paris",
    title: "Parc des Princes – Le Temple du PSG",
    description: "Plongez dans l'univers du Paris Saint-Germain au Parc des Princes. Visitez les coulisses du stade iconique, le musée du club, les vestiaires des stars et les loges VIP. Un incontournable pour tout fan Rouge et Bleu.",
    duration: 2,
    price: 750,
    rating: 4.8,
    reviews: 389,
    activities: ["stadium", "museum", "city-tour"],
    highlights: ["Visite officielle du Parc des Princes", "Musée du PSG", "Vestiaires & tunnel des joueurs", "Salle de presse & zone mixte", "Boutique PSG officielle", "Vue panoramique sur le stade"],
    image: "images/ParcdesPrinces.webp",
    popular: true,
    tag: "Best-seller",
  },
  {
    id: "sdf-1",
    country: "france",
    city: "Saint-Denis",
    title: "Stade de France – La Cathédrale des Bleus",
    description: "Le Stade de France, théâtre de la victoire des Bleus en 1998, vous ouvre ses portes. Visitez l'enceinte la plus grande de France, marchez sur la pelouse sacrée et revivez les plus grands moments du football français.",
    duration: 2,
    price: 699,
    rating: 4.9,
    reviews: 521,
    activities: ["stadium", "museum", "city-tour"],
    highlights: ["Visite du Stade de France (80 000 places)", "Musée de l'équipe de France", "Couloir des Champions 1998", "Pelouse & vestiaires officiels", "Salle des trophées des Bleus", "Expérience réalité augmentée"],
    image: "https://images.unsplash.com/photo-1489944440615-453fc2b6a9a9?w=900&q=80",
    popular: true,
    tag: "Incontournable",
  },
  {
    id: "lyon-1",
    country: "france",
    city: "Lyon",
    title: "Groupama Stadium – L'OL Park",
    description: "Le Groupama Stadium est l'un des stades les plus modernes d'Europe. Vivez une visite VIP du fief de l'Olympique Lyonnais : musée du club, loges premium, pelouse et découverte de l'OL Academy.",
    duration: 2,
    price: 600,
    rating: 4.7,
    reviews: 213,
    activities: ["stadium", "museum"],
    highlights: ["Visite du Groupama Stadium", "Musée de l'Olympique Lyonnais", "7 titres de champion de France", "Loges & tribune présidentielle", "OL Academy & centre de formation", "Boutique officielle OL"],
    image: "images/GroupamaStadium.jpg",
    popular: false,
    tag: null,
  },

  // ── ITALIE ────────────────────────────────────────────────
  {
    id: "mil-1",
    country: "italy",
    city: "Milan",
    title: "San Siro – Le Stade des Deux Géants",
    description: "San Siro est l'un des stades les plus mythiques du monde, partagé par l'AC Milan et l'Inter Milan. Cette visite unique vous fait traverser l'histoire de deux clubs légendaires, leurs trophées et la pelouse sacrée de la Serie A.",
    duration: 2,
    price: 799,
    rating: 4.9,
    reviews: 487,
    activities: ["stadium", "museum", "city-tour"],
    highlights: ["Visite de San Siro (Giuseppe Meazza)", "Musée AC Milan & Inter Milan", "Galerie des trophées Serie A & Champions League", "Vestiaires historiques", "Tribune d'honneur & loge présidentielle", "Boutiques officielles des deux clubs"],
    image: "images/SanSiro.webp",
    popular: true,
    tag: "Best-seller",
  },
  {
    id: "tur-1",
    country: "italy",
    city: "Turin",
    title: "Allianz Stadium – La Forteresse de la Juventus",
    description: "L'Allianz Stadium est le premier stade de Serie A entièrement dédié à un club : la Juventus. Visitez ce bijou architectural, le J-Museum, les 36 titres de champion d'Italie et les trophées européens bianconeri.",
    duration: 2,
    price: 750,
    rating: 4.8,
    reviews: 298,
    activities: ["stadium", "museum"],
    highlights: ["Visite de l'Allianz Stadium", "J-Museum (musée de la Juventus)", "36 Scudetti & 2 Ligues des Champions", "Vestiaires & tunnel des joueurs", "Loge VIP & tribune bianconera", "Boutique officielle Juventus"],
    image: "images/AllianzStadium.webp",
    popular: true,
    tag: "Coup de cœur",
  },
  {
    id: "nap-1",
    country: "italy",
    city: "Naples",
    title: "Stade Diego Armando Maradona – Le Temple de D10S",
    description: "Naples célèbre encore son dieu Maradona. Le stade rebaptisé en son honneur est un pèlerinage obligatoire. Visitez le musée napolitain, les fresques murales dans la ville et revivez les deux titres de Serie A offerts par El Pibe de Oro.",
    duration: 2,
    price: 829,
    rating: 4.9,
    reviews: 345,
    activities: ["stadium", "museum", "city-tour"],
    highlights: ["Visite du Stade Diego Armando Maradona", "Musée SSC Napoli & hommages à Maradona", "Galerie des 3 Scudetti", "Fresques murales Maradona dans Naples", "Vestiaires historiques", "Culture footballistique napolitaine"],
    image: "images/StadeDiegoArmandoMaradona.jpg",
    popular: true,
    tag: "Incontournable",
  },
  {
    id: "rom-1",
    country: "italy",
    city: "Rome",
    title: "Stadio Olimpico – Le Derby Éternel de Rome",
    description: "Le Stadio Olimpico abrite l'un des derbies les plus passionnés : AS Roma contre SS Lazio. Visitez ce stade historique ayant accueilli deux Coupes du Monde, les trophées des deux clubs et les coulisses d'un temple du calcio.",
    duration: 2,
    price: 699,
    rating: 4.7,
    reviews: 221,
    activities: ["stadium", "museum"],
    highlights: ["Visite du Stadio Olimpico", "Musée AS Roma & SS Lazio", "Histoire du Derby della Capitale", "Vestiaires & tunnel officiel", "Tribune Curva Sud & Curva Nord", "Boutiques officielles Roma & Lazio"],
    image: "https://images.unsplash.com/photo-1489944440615-453fc2b6a9a9?w=900&q=80",
    popular: false,
    tag: null,
  },

   // ── Allemagne ────────────────────────────────────────────
  {
    id: "lon-1",
    country: "germany",
    city: "Berlin",
    title: "Olympiastadion – Le Temple du Football Allemand",
    description: "L'Olympiastadion est le stade emblématique de l'Allemagne. Visitez ce monument architectural, les coulisses du stade et revivez ses moments légendaires.",
    duration: 2,
    price: 599,
    rating: 4.8,
    reviews: 496,
    activities: ["stadium", "museum", "city-tour"],
    highlights: ["Visite de l'Olympiastadion (74 000 places)", "Musée du football allemand", "Tunnel des joueurs & vestiaires nationaux", "Royal Box & loge présidentielle", "Trophées DFB-Pokal & Bundesliga", "Vue depuis le sommet de l'Arche (optionnel)"],
    image: "images/Olympiastadion.jpeg",
    popular: true,
    tag: "Incontournable",
  },
   {
    id: "mun-1",
    country: "germany",
    city: "Munich",
    title: "Allianz Arena –  surnommée le « Schlauchboot »",
    description: "L'Allianz Arena ne vaut pas seulement la peine les jours de matchs, mais tout au long de l'année. Le stade du FC Bayern Munich est une attraction à part entière.",
    duration: 3,
    price: 999,
    rating: 4.4,
    reviews: 156,
    activities: ["stadium", "museum", "city-tour"],
    highlights: ["Visite de l'Allianz Arena (70 000 places)", "Musée du football allemand", "Tunnel des joueurs & vestiaires nationaux", "Royal Box & loge présidentielle", "Trophées DFB-Pokal & Bundesliga", "Vue depuis le sommet de l'Arche (optionnel)"],
    image: "images/AllianzArena.jpg",
    popular: true,
    tag: "Légende",
  },
  {
    id: "dor-1",
    country: "germany",
    city: "Dortmund",
    title: "Westfalenstadion –  Signal Iduna Park",
    description: "L'Allianz Arena ne vaut pas seulement la peine les jours de matchs, mais tout au long de l'année. Le stade du FC Bayern Munich est une attraction à part entière.",
    duration: 3,
    price: 899,
    rating: 4.4,
    reviews: 156,
    activities: ["stadium", "museum"],
    highlights: ["Visite de Westfalenstadion (81,365 places)", "Musée du football allemand", "Tunnel des joueurs & vestiaires nationaux", "Trophées DFB-Pokal & Bundesliga", "Vue depuis le sommet de l'Arche (optionnel)"],
    image: "images/Westfalenstadion.jpg",
    popular: true,
    tag: "Mythique",
  },


  // ── ANGLETERRE ────────────────────────────────────────────
  {
    id: "lon-1",
    country: "england",
    city: "Londres",
    title: "Wembley Stadium – L'Arche Sacrée",
    description: "Wembley est la cathédrale du football anglais. 90 000 places, l'Arche iconique visible à des kilomètres. Visitez les coulisses du plus grand stade du Royaume-Uni et revivez ses moments légendaires.",
    duration: 2,
    price: 899,
    rating: 4.9,
    reviews: 612,
    activities: ["stadium", "museum", "city-tour"],
    highlights: ["Visite de Wembley Stadium (90 000 places)", "Musée de l'équipe d'Angleterre", "Tunnel des joueurs & vestiaires nationaux", "Royal Box & loge présidentielle", "Trophées FA Cup & Euro", "Vue depuis le sommet de l'Arche (optionnel)"],
    image: "images/WembleyStadium.jpg",
    popular: true,
    tag: "Incontournable",
  },
  {
    id: "man-1",
    country: "england",
    city: "Manchester",
    title: "Old Trafford – Le Théâtre des Rêves",
    description: "Old Trafford, le Théâtre des Rêves, est la maison de Manchester United. Visitez ce stade légendaire, le musée United et plongez dans l'histoire du club le plus populaire d'Angleterre, de Busby à Ferguson.",
    duration: 2,
    price: 950,
    rating: 4.8,
    reviews: 478,
    activities: ["stadium", "museum"],
    highlights: ["Visite d'Old Trafford (74 000 places)", "Manchester United Museum", "20 titres de Premier League", "3 Ligues des Champions", "Vestiaires & tunnel des joueurs", "Statue de Sir Alex Ferguson"],
    image: "images/OldTrafford.avif",
    popular: true,
    tag: "Théâtre des Rêves",
  },
  {
    id: "liv-1",
    country: "england",
    city: "Liverpool",
    title: "Anfield – You'll Never Walk Alone",
    description: "Anfield est l'âme du Liverpool FC. L'hymne You'll Never Walk Alone résonne dans chaque couloir. Visitez la Kop légendaire, le musée LFC, les trophées de Premier League et les 6 Coupes d'Europe du club de la Mersey.",
    duration: 2,
    price: 959,
    rating: 4.9,
    reviews: 534,
    activities: ["stadium", "museum"],
    highlights: ["Visite d'Anfield Stadium", "LFC Museum", "La Kop (tribune légendaire)", "6 Ligues des Champions", "Vestiaires & panneau This Is Anfield", "Mémorial Hillsborough"],
    image: "images/Anfield.jpeg",
    popular: true,
    tag: "Légende",
  },

  // ── PORTUGAL ─────────────────────────────────────────────
  {
    id: "lis-1",
    country: "portugal",
    city: "Lisbonne",
    title: "Estádio da Luz – L'Arène de la Lumière",
    description: "Le Estádio da Luz est le plus grand stade du Portugal et l'antre du Benfica Lisbonne. Visitez ce monument du football lusitanien, son musée retraçant les glorieuses soirées européennes et le panthéon des légendes de l'Aigle.",
    duration: 2,
    price: 850,
    rating: 4.8,
    reviews: 234,
    activities: ["stadium", "museum", "city-tour"],
    highlights: ["Visite du Estádio da Luz (64 000 places)", "Musée officiel Benfica", "2 Coupes d'Europe & 38 titres nationaux", "Vestiaires & tunnel des joueurs", "Galerie des légendes (Eusébio, Chalana)", "Boutique officielle Benfica"],
    image: "images/EstádiodaLuz.jpeg",
    popular: true,
    tag: "Best-seller",
  },
  {
    id: "por-1",
    country: "portugal",
    city: "Porto",
    title: "Estádio do Dragão – Le Repaire du Dragon",
    description: "Le Estádio do Dragão est l'emblème du FC Porto. Visitez cette enceinte inaugurée lors de l'Euro 2004, son musée, la galerie des champions et revivez la Ligue des Champions 2004 remportée sous Mourinho.",
    duration: 2,
    price: 799,
    rating: 4.7,
    reviews: 167,
    activities: ["stadium", "museum"],
    highlights: ["Visite du Estádio do Dragão", "Musée FC Porto", "Ligue des Champions 2004 (Mourinho)", "Galerie des légendes Porto", "Vestiaires & coulisses du stade", "Boutique officielle FC Porto"],
    image: "images/EstádiodoDragão.jpeg",
    popular: false,
    tag: null,
  },

  // ── PAYS-BAS ──────────────────────────────────────────────
  {
    id: "ams-1",
    country: "netherlands",
    city: "Amsterdam",
    title: "Johan Cruyff ArenA – Le Temple du Football Total",
    description: "L'Ajax Amsterdam et son stade portant le nom du génie Johan Cruyff. Visitez l'enceinte moderne d'Amsterdam, le musée Ajax et les trophées de 4 Coupes d'Europe.",
    duration: 2,
    price: 599,
    rating: 4.8,
    reviews: 198,
    activities: ["stadium", "museum", "city-tour"],
    highlights: ["Visite de la Johan Cruyff ArenA", "Musée Ajax Amsterdam", "4 Coupes d'Europe & 36 titres nationaux", "Hommage à Johan Cruyff", "Vestiaires & terrain d'entraînement", "Culture footballistique néerlandaise"],
    image: "images/JohanCruyffArenA.jpg",
    popular: true,
    tag: "Football Total",
  },
  {
    id: "rot-1",
    country: "netherlands",
    city: "Rotterdam",
    title: "De Kuip – La Cuvette de Feyenoord",
    description: "De Kuip est l'un des stades les plus atmosphériques d'Europe. Feyenoord Rotterdam, vainqueur de la Coupe des clubs champions en 1970, vous accueille dans son antre légendaire.",
    duration: 2,
    price: 550,
    rating: 4.6,
    reviews: 134,
    activities: ["stadium", "museum"],
    highlights: ["Visite de De Kuip (51 000 places)", "Musée Feyenoord Rotterdam", "Coupe d'Europe 1970", "Coulisses & vestiaires historiques", "Ambiance tribune historique", "Boutique officielle Feyenoord"],
    image: "images/DeKuip.jpg",
    popular: false,
    tag: null,
  },

  // ── BRÉSIL ────────────────────────────────────────────────
  {
    id: "rio-1",
    country: "brazil",
    city: "Rio de Janeiro",
    title: "Maracanã – La Cathédrale du Football Mondial",
    description: "Le Maracanã est le stade le plus mythique de la planète football. Théâtre du Maracanazo en 1950, de la Coupe du Monde 2014 et des JO 2016, il incarne 70 ans d'histoire du jogo bonito.",
    duration: 2,
    price: 1499,
    rating: 5.0,
    reviews: 378,
    activities: ["stadium", "museum", "city-tour"],
    highlights: ["Visite du Maracanã (78 000 places)", "Musée du football brésilien", "Mémorial du Maracanazo 1950", "Galerie des légendes (Pelé, Zico, Ronaldo)", "Pelouse sacrée & vestiaires", "Vue panoramique sur Rio de Janeiro"],
    image: "images/Maracanã.jpg",
    popular: true,
    tag: "Mythique",
  },
  {
    id: "sao-1",
    country: "brazil",
    city: "São Paulo",
    title: "Arena Corinthians & Musée du Football",
    description: "São Paulo est la capitale brésilienne du football. Visitez l'Arena Corinthians et le Musée du Football, l'un des plus beaux musées sportifs du monde avec sa galerie des Coupes du Monde brésiliennes.",
    duration: 2,
    price: 1599,
    rating: 4.8,
    reviews: 312,
    activities: ["stadium", "museum", "city-tour"],
    highlights: ["Visite de l'Arena Corinthians", "Musée du Football de São Paulo", "Galerie des 5 Coupes du Monde brésiliennes", "Histoire de Corinthians, Palmeiras, São Paulo FC", "Vestiaires & pelouse de l'Arena", "Culture footballistique pauliste"],
    image: "images/ArenaCorinthians.webp",
    popular: false,
    tag: null,
  },
];

const FEATURED_CIRCUITS = CIRCUITS.filter(c => c.popular).slice(0, 6);

const TESTIMONIALS = [
  { name: "Thomas R.", country: "France", avatar: "TR", text: "La visite du Camp Nou était tout simplement magique. Marcher dans le tunnel des joueurs, toucher la pelouse… j'avais 10 ans à nouveau. Une expérience parfaitement organisée.", rating: 5, circuit: "Camp Nou & Musée du FC Barcelone" },
  { name: "Mehdi K.", country: "France", avatar: "MK", text: "Le Maracanã m'a coupé le souffle. L'histoire de ce stade est palpable à chaque pas. Le musée brésilien est l'un des plus beaux que j'ai vus. Je recommande à 1000%.", rating: 5, circuit: "Maracanã – La Cathédrale du Football Mondial" },
  { name: "Laura B.", country: "Belgique", avatar: "LB", text: "Anfield m'a ému aux larmes. Entendre YNWA résonner dans les couloirs vides, toucher le panneau This Is Anfield… C'est une expérience spirituelle pour tout fan de football.", rating: 5, circuit: "Anfield – You'll Never Walk Alone" },
  { name: "Pierre D.", country: "France", avatar: "PD", text: "Old Trafford et son musée dépassent toutes les attentes. L'histoire de Ferguson, les trophées, les anecdotes… Mon fils de 14 ans en parle encore des semaines après.", rating: 5, circuit: "Old Trafford – Le Théâtre des Rêves" },
];

const SERVICES = [
  { icon: "🏟️", title: "Visites de Stades", description: "Accédez aux coulisses des stades les plus légendaires du monde entier" },
  { icon: "🏆", title: "Musées des Clubs", description: "Découvrez les trophées et l'histoire des plus grands clubs en priorité" },
  { icon: "⚽", title: "Expériences Football", description: "Vestiaires, tunnels, pelouses : vivez le football de l'intérieur" },
  { icon: "🗺️", title: "Circuits Guidés", description: "Guides experts passionnés de football pour chaque destination" },
  { icon: "📸", title: "Séances Photo", description: "Photos souvenirs professionnelles sur la pelouse des grands stades" },
  { icon: "🏨", title: "Hôtels Sélectionnés", description: "Hébergements de qualité au cœur des quartiers des stades" },
];
